name: Terraform workflow - network

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/network/**'

jobs:
  tf_plan_apply:
    uses: Crayon-HU/github-workflows/.github/workflows/tf_workflow_plan_apply.yml@config-step
    with:
      runner: OCI_hosted
      backend_type: pg
      config_directory: terraform/network
      # checkov_scan: true
      provider_oci: true
      github_owner: ${{ vars.GH_CRAYONHU_ORG }}

    secrets:
      # aws_access_key: ${{ secrets.OCI_CRAYON_LEDERMAYER_ACCESS_KEY }}
      # aws_secret_key: ${{ secrets.OCI_CRAYON_LEDERMAYER_SECRET_KEY }}
      pg_backend_username: ${{ secrets.OCI_PGBACKEND_USER }}
      pg_backend_password: ${{ secrets.OCI_PGBACKEND_PASSWORD }}
      oci_tenancy: ${{ secrets.OCI_CRAYON_TENANCY }}
      oci_user: ${{ secrets.OCI_CRAYON_LEDERMAYER_USER }}
      oci_key: ${{ secrets.OCI_CRAYON_LEDERMAYER_KEY }}
      oci_fingerprint: ${{ secrets.OCI_CRAYON_LEDERMAYER_FINGERPRINT }}
      github_pat: ${{ secrets.GH_CRAYONHU_PAT }}