name: Terraform workflow - container instance

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/container-instance/**'

jobs:
  tf_step_plan:
    runs-on: OCI_hosted
    name: Inject TF_VARS
    env:
      TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
      TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

  tf_plan_apply_default:
    uses: Crayon-HU/github-workflows/.github/workflows/tf_workflow_plan_apply.yml@environments
    with:
      runner: OCI_hosted
      backend_type: s3
      infra_repo: terraform-infra-oci-crayonas-openlz-core
      infra_repo_ref: bootstrap
      config_repo: terraform-config-oci-crayonas-openlz-core
      config_repo_ref: init
      config_directory: container-instance
      # checkov_scan: true
      provider_oci: true
      github_owner: ${{ vars.GH_CRAYONHU_ORG }}
    secrets:
      aws_access_key: ${{ secrets.OCI_CRAYONHU_SPINNERBOT_ACCESS_KEY }}
      aws_secret_key: ${{ secrets.OCI_CRAYONHU_SPINNERBOT_SECRET_KEY }}
      oci_tenancy: ${{ secrets.OCI_CRAYON_TENANCY }}
      oci_user: ${{ secrets.OCI_CRAYON_LEDERMAYER_USER }}
      oci_key: ${{ secrets.OCI_CRAYON_LEDERMAYER_KEY }}
      oci_fingerprint: ${{ secrets.OCI_CRAYON_LEDERMAYER_FINGERPRINT }}
      github_pat: ${{ secrets.GH_CRAYONHU_PAT }}